name: Price Tracker

on:
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:

jobs:
  check-price:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Restore state
        uses: actions/cache/restore@v4
        with:
          path: price_state.json
          key: price-state

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python pret_bot.py

      - name: Save state
        uses: actions/cache/save@v4
        with:
          path: price_state.json
          key: price-state-${{ github.run_id }}
